services:
    _defaults:
        public: true

    Oro\Bridge\MarketingCRM\Controller\CustomerController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
